name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate icons
        run: npm run generate:icons

      - name: Build for Mac
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Mac artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QuantBot-Mac
          path: release/*/QuantBot-Mac-*-Installer.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate icons
        run: npm run generate:icons

      - name: Setup VC++ tools for native builds
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --quiet --norestart" --yes --no-progress

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Windows Portable
        run: npm run build:win:portable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QuantBot-Windows-Portable
          path: release/*/QuantBot-Windows-*-Setup.exe

  release:
    needs: [build-mac, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Mac artifacts
        uses: actions/download-artifact@v4
        with:
          name: QuantBot-Mac
          path: artifacts/

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: QuantBot-Windows-Portable
          path: artifacts/

      - name: Create Release
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          RELEASE_NOTES="Automated release $VERSION

          ## Downloads
          - Mac: QuantBot-Mac-${VERSION#v}-Installer.dmg
          - Windows Portable: QuantBot-Windows-${VERSION#v}-Setup.exe"

          gh release create "$VERSION" \
            --title "Release $VERSION" \
            --notes "$RELEASE_NOTES" \
            artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
