name: CI - build installers

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - master

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build (mac dmg)
        run: npm run build -- --publish=never

      - name: Set up PAT for release
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Upload mac artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-installers
          path: release/**/QuantBot-Mac-*.dmg*

  build-windows-portable:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build (windows portable)
        run: npm run build:win:portable

      - name: Upload windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installers
          path: release/**/QuantBot-Windows-*-Setup.*
