name: CI - build installers (simplified)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - master

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Say hi
        run: echo "ci-build simplified job running"
