name: CI - build installers (partial)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - master

jobs:
  build-windows-portable:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Quick echo
        run: echo "partial windows job running"
