name: CI - build test

on:
  workflow_dispatch:

jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "CI test: workflow runner is working"
