name: CI - minimal debug

on:
  push:
    branches:
      - master

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "minimal debug workflow running"
