name: CI - temporary windows build + release

on:
  workflow_dispatch:

jobs:
  build-and-release-windows:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (windows portable)
        run: npm run build:win:portable:cross -- --publish never

      - name: Upload windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installers
          path: |
            release/**/QuantBot-Windows-*-Setup.exe
            release/**/win-unpacked/**

      - name: Get package version
        id: get_version
        shell: bash
        run: |
          version=$(node -p "require('./package.json').version")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and attach artifacts
        uses: ncipollo/release-action@v1
        with:
          # Use the PAT we added to repository secrets so the action can create releases
          token: ${{ secrets.GH_PAT }}
          tag: v${{ steps.get_version.outputs.version }}
          # Attach the artifact uploaded above by name
          artifacts: windows-installers
          # Allow updating an existing release with the same tag (useful for test runs)
          allowUpdates: true
